[build]
  command = "npm run build"
  publish = "dist/shotplan/browser"

[build.environment]
  NODE_VERSION = "22.22.0"

[[plugins]]
  package = "@netlify/angular-runtime"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
